spring.application.name=sgcm-api


# propriedades de conexao com o banco de dados
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sgcm_db
spring.datasource.username=root
spring.datasource.password=root